use_frameworks!
platform :ios, '9.0'

target 'AssetView_Example' do
  pod 'AssetView', :path => '../'

  target 'AssetView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
